name: apilab
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2
dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.0.0
  json_webtoken: ^3.0.1
  shelf_static: ^1.0.0

dev_dependencies:
  shelf_hotreload: ^0.1.0

  test: ^1.16.0
